# These are supported funding model platforms
# Once you generate your Paystack link, replace "INSERT_YOUR_PAYSTACK_LINK_HERE" with your actual link

custom: ['https://paystack.com/pay/INSERT_YOUR_PAYSTACK_LINK_HERE', 'https://drogonclaw.xyz']
