# These are supported funding model platforms

patreon: 0xP4X
ko_fi: 0xP4X
# open_collective: # Replace with a single Open Collective username
custom: ['https://drogonclaw.xyz', 'https://buymeacoffee.com/0xP4X']
