package whitebox

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Write renders the Markdown and SARIF reports and writes them to OutDir.
// It returns the path to the Markdown report.
func (r *Report) Write(outDir string) (string, error) {
	if outDir == "" {
		outDir = "whitebox_reports"
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	stamp := r.Started.Format("20060102-150405")
	mdPath := filepath.Join(outDir, fmt.Sprintf("whitebox-%s.md", stamp))
	sarifPath := filepath.Join(outDir, fmt.Sprintf("whitebox-%s.sarif", stamp))

	if err := os.WriteFile(mdPath, []byte(r.renderMarkdown()), 0o644); err != nil {
		return "", err
	}
	if err := os.WriteFile(sarifPath, []byte(r.renderSARIF()), 0o644); err != nil {
		return "", err
	}
	return mdPath, nil
}

func (r *Report) renderMarkdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# DrogonClaw White-Box Assessment\n\n")
	fmt.Fprintf(&b, "- **Target:** %s\n", na(r.TargetURL))
	fmt.Fprintf(&b, "- **Source:** %s\n", na(r.RepoPath))
	fmt.Fprintf(&b, "- **Session:** %s\n", na(r.SessionID))
	fmt.Fprintf(&b, "- **Started:** %s\n", r.Started.Format(time.RFC3339))
	fmt.Fprintf(&b, "- **Finished:** %s\n", r.Finished.Format(time.RFC3339))
	fmt.Fprintf(&b, "- **Tool calls:** %d\n", r.ToolCalls)
	fmt.Fprintf(&b, "- **Findings:** %d (%d verified)\n\n", len(r.Findings), countVerified(r.Findings))

	fmt.Fprintf(&b, "## Summary by class\n\n")
	byClass := map[string]int{}
	for _, f := range r.Findings {
		byClass[f.Class]++
	}
	for _, c := range []string{"injection", "xss", "ssrf", "authn", "authz"} {
		if n, ok := byClass[c]; ok {
			fmt.Fprintf(&b, "- **%s**: %d\n", strings.ToUpper(c), n)
		}
	}
	if len(byClass) == 0 {
		fmt.Fprintf(&b, "_No findings._\n")
	}

	fmt.Fprintf(&b, "\n## Findings\n\n")
	if len(r.Findings) == 0 {
		b.WriteString("_No findings were produced. This is a candidate-only or clean run._\n")
	}
	for _, f := range r.Findings {
		status := "candidate"
		if f.Verified {
			status = "VERIFIED"
		}
		fmt.Fprintf(&b, "### %s — %s [%s]\n", f.ID, f.Title, strings.ToUpper(string(f.Severity)))
		fmt.Fprintf(&b, "- **Class:** %s\n", f.Class)
		fmt.Fprintf(&b, "- **Status:** %s\n", status)
		fmt.Fprintf(&b, "- **Target:** %s\n", f.Target)
		fmt.Fprintf(&b, "- **Location:** %s\n", f.Location)
		if f.Source != "" {
			fmt.Fprintf(&b, "- **Source:** %s\n", f.Source)
		}
		if f.Evidence != "" {
			fmt.Fprintf(&b, "- **Evidence:**\n```\n%s\n```\n", f.Evidence)
		}
		if f.PoC != "" {
			fmt.Fprintf(&b, "- **PoC:** %s\n", f.PoC)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "---\n*Generated by DrogonClaw WhiteBox. AUTHORIZED TESTING ONLY.*\n")
	return b.String()
}

func (r *Report) renderSARIF() string {
	type sarifResult struct {
		RuleID    string            `json:"ruleId"`
		Level     string            `json:"level"`
		Message   map[string]string `json:"message"`
		Locations []map[string]any  `json:"locations"`
		Props     map[string]any    `json:"properties"`
	}
	level := func(s Severity) string {
		switch s {
		case SeverityCritical, SeverityHigh:
			return "error"
		case SeverityMedium:
			return "warning"
		default:
			return "note"
		}
	}
	results := make([]sarifResult, 0, len(r.Findings))
	for _, f := range r.Findings {
		loc := map[string]any{
			"physicalLocation": map[string]any{
				"artifactLocation": map[string]any{"uri": f.Target},
				"region":           map[string]any{"snippet": map[string]any{"text": f.Evidence}},
			},
		}
		results = append(results, sarifResult{
			RuleID:  f.Class,
			Level:   level(f.Severity),
			Message: map[string]string{"text": f.Title},
			Locations: []map[string]any{
				loc,
			},
			Props: map[string]any{
				"verified": f.Verified,
				"severity": string(f.Severity),
				"poc":      f.PoC,
				"source":   f.Source,
			},
		})
	}
	doc := map[string]any{
		"version": "2.1.0",
		"$schema": "https://json.schemastore.org/sarif-2.1.0.json",
		"runs": []map[string]any{
			{
				"tool": map[string]any{
					"driver": map[string]any{
						"name":           "DrogonClaw WhiteBox",
						"informationUri": "https://github.com/0xP4X/drogonclaw",
						"version":        "whitebox-0.1",
					},
				},
				"results": results,
			},
		},
	}
	buf, _ := json.MarshalIndent(doc, "", "  ")
	return string(buf)
}

func countVerified(fs []Finding) int {
	n := 0
	for _, f := range fs {
		if f.Verified {
			n++
		}
	}
	return n
}

func na(s string) string {
	if s == "" {
		return "_n/a_"
	}
	return s
}
