package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/0xP4X/drogonclaw-go/internal/memory"
	"github.com/jung-kurt/gofpdf"
)

// GeneratePDFReport creates a professional PDF penetration test report from the graph data.
func GeneratePDFReport(graph *memory.Graph) (string, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Add Title
	pdf.SetFont("Arial", "B", 24)
	pdf.CellFormat(190, 20, "DrogonClaw Security Assessment Report", "0", 1, "C", false, 0, "")
	
	// Add Date
	pdf.SetFont("Arial", "I", 12)
	dateStr := fmt.Sprintf("Generated on: %s", time.Now().Format("January 2, 2006"))
	pdf.CellFormat(190, 10, dateStr, "0", 1, "C", false, 0, "")
	pdf.Ln(10)
	
	// Executive Summary
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(190, 10, "1. Executive Summary", "0", 1, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	
	graphJSON := graph.GetFullJSON()
	
	summaryText := "This document contains the automated security assessment findings generated by DrogonClaw. " +
		"The assessment covered the target infrastructure and identified the following assets and potential vulnerabilities."
	pdf.MultiCell(190, 6, summaryText, "0", "L", false)
	pdf.Ln(5)

	// Findings / Raw Data snippet (Since we don't have LLM context here for full English sentences)
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(190, 10, "2. Technical Details (Graph Snapshot)", "0", 1, "L", false, 0, "")
	pdf.SetFont("Courier", "", 10)
	
	// Truncate graph JSON to avoid massive PDF sizes in this basic generator
	if len(graphJSON) > 3000 {
		graphJSON = graphJSON[:3000] + "\n... (Truncated)"
	}
	
	lines := strings.Split(graphJSON, "\n")
	for _, line := range lines {
		pdf.MultiCell(190, 5, line, "0", "L", false)
	}

	_ = os.MkdirAll("reports", 0755)
	filename := filepath.Join("reports", fmt.Sprintf("drogonclaw_report_%d.pdf", time.Now().Unix()))

	err := pdf.OutputFileAndClose(filename)
	if err != nil {
		return "", fmt.Errorf("failed to save PDF: %w", err)
	}

	return filename, nil
}
